trigger: none
pool: app pool
stages:
- stage: BuildGetTask
  displayName: build the Get task
  jobs:
  - job: GetTaskjob
    displayName: build the GetTask
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-SC'
        repository: 'GetTask'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
