trigger: none
pool: app pool
stages:
- stage: DeleteTask
  displayName: build the Delete task
  jobs:
  - job: DeleteTaskjob
    displayName: build the DeleteTask
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-SC'
        repository: 'DeleteTask'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
